#!/bin/sh
#
# Dummy executable so any scripts that tries to be nice and install Homebrew for you
# without realizing the world outside Homebrew exists stop breaking your setup.
#
# Screw monoculture.
#

echo "Screw Homebrew."
exit 1
