---
## Elixir
##

- name: install elixir plugin via asdf
  git:
    repo: https://github.com/asdf-vm/asdf-elixir.git
    dest: "{{asdf_path}}/plugins/elixir"

- name: install elixir {{elixir_version}} via asdf
  shell: "{{asdf_bin}}/asdf install elixir {{elixir_version}}"
  args:
    creates: "{{elixir_version_path}}"


## Setting default
##

- name: update elixir defaults
  shell: |
    {{asdf_bin}}/asdf global elixir {{elixir_version}} &&
    {{asdf_bin}}/asdf reshim elixir
  changed_when: false
