---
- name: install golang plugin via asdf
  git:
    repo: https://github.com/kennyp/asdf-golang.git
    dest: "{{asdf_path}}/plugins/golang"

- name: install golang {{golang_version}} via asdf
  command: "{{asdf_bin}}/asdf install golang {{golang_version}}"
  args:
    creates: "{{golang_version_path}}"

- name: set golang {{golang_version}} as default
  command: "{{asdf_bin}}/asdf global golang {{golang_version}}"
  changed_when: false

- name: ensure gopath directory
  file:
    path: ~/Dev/go/
    state: directory
    recurse: yes

- name: install golang packages
  command: "{{golang_goroot}}/bin/go get -u {{item}}"
  args:
    creates: "~/Dev/go/src/{{item}}"
  environment:
    GOPATH: "{{golang_gopath}}"
    GOROOT: "{{golang_goroot}}"
  with_items: "{{golang_packages}}"

- name: update golang {{golang_version}} shims
  command: "{{asdf_bin}}/asdf reshim golang"
  changed_when: false
