---
## Golang
##

- name: install golang plugin via asdf
  git:
    repo: https://github.com/kennyp/asdf-golang.git
    dest: "{{asdf_path}}/plugins/golang"

- name: install golang {{golang_version}} via asdf
  command: "{{asdf_bin}}/asdf install golang {{golang_version}}"
  args:
    creates: "{{golang_version_path}}"


## Setting up GOPATH
##

- name: ensure gopath directory
  file:
    path: ~/Dev/go/
    state: directory
    recurse: yes

- name: install golang packages
  command: "{{golang_goroot}}/bin/go get -u {{item}}"
  args:
    creates: "~/Dev/go/src/{{item}}"
  environment:
    GOPATH: "{{golang_gopath}}"
    GOROOT: "{{golang_goroot}}"
  with_items: "{{golang_packages}}"
  when: golang_packages


## Setting default
##

- name: update golang defaults
  shell: |
    {{asdf_bin}}/asdf global golang {{golang_version}} &&
    {{asdf_bin}}/asdf reshim golang
  changed_when: false
