---
## Nim
##

- name: install nim plugin via asdf
  git:
    repo: https://github.com/rfrancis/asdf-nim.git
    dest: "{{asdf_path}}/plugins/nim"

- name: install nim {{nim_version}} via asdf
  command: "{{asdf_bin}}/asdf install nim v{{nim_version}}"
  args:
    creates: "{{nim_version_path}}"


## Setting default
##

- name: update nim defaults
  shell: |
    {{asdf_bin}}/asdf global nim v{{nim_version}} &&
    {{asdf_bin}}/asdf reshim nim
  changed_when: false
