---
## Ruby
##

- name: install ruby plugin via asdf
  git:
    repo: https://github.com/sirn/asdf-ruby.git
    dest: "{{asdf_path}}/plugins/ruby"
    version: "fix-patch"

# Some packages e.g. ruby ffi doesn't support building with clang on FreeBSD.
# Ruby will use the CC used to build Ruby itself, so we're setting CC here.
# See also https://github.com/ffi/ffi/issues/622
- name: install ruby {{ruby_version}} via asdf
  command: "{{asdf_bin}}/asdf install ruby {{ruby_version}}"
  args:
    creates: "{{ruby_version_path}}"
  environment:
    CC: "{{gcc_bin}}"
    MAKE: "{{gmake_bin}}"

- name: install ruby packages
  gem:
    name: "{{item}}"
    state: latest
    user_install: false
    executable: "{{ruby_version_path}}/bin/gem"
  with_items: "{{ruby_packages}}"
  when: ruby_packages


## Setting default
##

- name: update ruby defaults
  shell: |
    {{asdf_bin}}/asdf global ruby {{ruby_version}} &&
    {{asdf_bin}}/asdf reshim ruby
  changed_when: false
