---
- name: install rust plugin via asdf
  git:
    repo: https://github.com/code-lever/asdf-rust
    dest: "{{asdf_path}}/plugins/rust"

- name: install rust {{rust_version}} via asdf
  command: "{{asdf_bin}}/asdf install rust {{rust_version}}"
  args:
    creates: "{{rust_version_path}}"

- name: set rust {{rust_version}} as default
  command: "{{asdf_bin}}/asdf global rust {{rust_version}}"
  changed_when: false

- name: create rust source directory
  file: path=~/.local/src/rust state=directory recurse=yes

- name: extract rust source for {{rust_version}}
  shell: |
    mkdir -p ~/.local/src/rust/rustc-{{rust_version}} &&
    curl https://static.rust-lang.org/dist/rustc-{{rust_version}}-src.tar.gz |
    tar -xvzf - --strip-components 1 -C ~/.local/src/rust/rustc-{{rust_version}}
  args:
    warn: no
    creates: "~/.local/src/rust/rustc-{{rust_version}}"

- name: link rust source
  file:
    src: ~/.local/src/rust/rustc-{{rust_version}}
    path: ~/.local/src/rust/current
    state: link
    force: yes

- name: install rust packages
  command: "{{rust_version_path}}/bin/cargo install {{item.name}}"
  args:
    creates: ~/.cargo/bin/{{item.binary}}
  with_items: "{{rust_packages}}"
  environment:
    PATH: "{{rust_version_path}}/bin:{{env_path}}"

- name: update rust {{rust_version}} shims
  command: "{{asdf_bin}}/asdf reshim rust"
  changed_when: false
