#!/bin/sh
#
# Small wrapper to make some software happy
# (a.k.a. a brutal way to make python-build uses MacPorts)
#

_install() {
    exit 1
}

_prefix() {
    echo "/opt/local"
}

_list() {
    echo
}

main() {
    case "$1" in
    --prefix) _prefix ;;
    list) _list ;;
    install) _install ;;
    esac
}

main "$@"
