---
## Install dnscrypt-proxy
##

- name: install dnscrypt-proxy service
  homebrew:
    name: dnscrypt-proxy
    state: latest
  notify:
    - restart dnscrypt-proxy launchd service


## Configure dnscrypt-proxy
##

- name: configure dnscrypt-proxy
  become: yes
  copy:
    src: dnscrypt-proxy/dnscrypt-proxy.toml
    dest: /usr/local/etc/dnscrypt-proxy.toml
    owner: nobody
    group: nobody
  notify:
    - restart dnscrypt-proxy launchd service


## Register dnscrypt-proxy service
##

- name: enable dnscrypt-proxy service
  become: yes
  brew_services:
    name: dnscrypt-proxy
    state: started
