#!/bin/sh
#
# Some packages require `tar` to behave like GNU tar, with support for -x without
# -z or -j, or support --strip-components which are not POSIX. FreeBSD support
# both behaviors, probably for compatibility reasons, but OpenBSD doesn't.
#
# Since those packages usually don't even look for `gtar`, this hack of putting
# `tar` command that execvc into `gtar` is required.
#

case "$(uname)" in
    OpenBSD ) exec gtar "$@";;
    * ) exec tar "$@";;
esac
