/**
 * Smart Compact Extension for Pi Coding Agent
 *
 * Uses a configurable model for session compaction instead of the default model.
 * The provider/model pair is read from ~/.pi/agent/custom/smart-compact/config.json generated by Nix config.
 * Falls back to default compaction if the configured model is unavailable.
 */

import { complete } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import {
  convertToLlm,
  serializeConversation,
} from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const configPath = path.join(
  os.homedir(),
  ".pi/agent/custom/smart-compact/config.json",
);

interface SmartCompactAutoConfig {
  enable?: boolean;
  maxContextTokens?: number;
  contextRatio?: number;
}

interface NormalizedAutoCompactConfig {
  maxContextTokens: number;
  contextRatio: number;
}

interface SmartCompactConfig {
  provider: string;
  model: string;
  maxTokens?: number;
  autoCompact?: SmartCompactAutoConfig;
}

const DEFAULT_AUTO_COMPACT_MAX_CONTEXT_TOKENS = 150_000;
const DEFAULT_AUTO_COMPACT_CONTEXT_RATIO = 0.8;

let compactionConfig: SmartCompactConfig | null = null;

try {
  if (fs.existsSync(configPath)) {
    const customConfig: SmartCompactConfig = JSON.parse(
      fs.readFileSync(configPath, "utf-8"),
    );
    if (customConfig.provider && customConfig.model) {
      compactionConfig = customConfig;
    }
  }
} catch {
  // Config missing or invalid - extension will be a no-op
}

function getPositiveNumber(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? value
    : fallback;
}

function getRatio(value: unknown, fallback: number): number {
  return typeof value === "number" &&
    Number.isFinite(value) &&
    value > 0 &&
    value <= 1
    ? value
    : fallback;
}

function getAutoCompactConfig(): NormalizedAutoCompactConfig | undefined {
  if (compactionConfig?.autoCompact?.enable !== true) {
    return;
  }

  return {
    maxContextTokens: getPositiveNumber(
      compactionConfig.autoCompact.maxContextTokens,
      DEFAULT_AUTO_COMPACT_MAX_CONTEXT_TOKENS,
    ),
    contextRatio: getRatio(
      compactionConfig.autoCompact.contextRatio,
      DEFAULT_AUTO_COMPACT_CONTEXT_RATIO,
    ),
  };
}

function getAutoCompactThreshold(
  contextWindow: number,
  autoConfig: NormalizedAutoCompactConfig,
): number | undefined {
  if (!Number.isFinite(contextWindow) || contextWindow <= 0) {
    return;
  }

  const threshold = Math.min(
    autoConfig.maxContextTokens,
    Math.floor(contextWindow * autoConfig.contextRatio),
  );

  return Number.isFinite(threshold) && threshold > 0 ? threshold : undefined;
}

export default function (pi: ExtensionAPI) {
  // Skip if no config
  if (!compactionConfig) {
    return;
  }

  let previousTokens: number | null | undefined;
  let autoCompactionInProgress = false;

  pi.on("agent_end", (_event, ctx) => {
    const autoCompactConfig = getAutoCompactConfig();
    if (!autoCompactConfig || autoCompactionInProgress) {
      return;
    }

    const usage = ctx.getContextUsage();
    if (!usage) {
      return;
    }

    const currentTokens = usage.tokens;
    if (currentTokens === null) {
      return;
    }

    const contextWindow = usage.contextWindow || ctx.model?.contextWindow;
    if (!contextWindow) {
      return;
    }

    const threshold = getAutoCompactThreshold(contextWindow, autoCompactConfig);
    if (!threshold) {
      return;
    }

    const wasBelowOrAtThreshold =
      previousTokens === undefined ||
      previousTokens === null ||
      previousTokens <= threshold;
    previousTokens = currentTokens;
    if (!wasBelowOrAtThreshold || currentTokens <= threshold) {
      return;
    }

    autoCompactionInProgress = true;
    if (ctx.hasUI) {
      ctx.ui.notify(
        `Auto-compacting ${currentTokens.toLocaleString()} tokens at threshold ${threshold.toLocaleString()}...`,
        "info",
      );
    }

    ctx.compact({
      customInstructions:
        "Auto-compaction triggered because context usage exceeded the configured threshold. Preserve current task state, decisions, modified files, verification results, blockers, and next actions.",
      onComplete: () => {
        autoCompactionInProgress = false;
        previousTokens = null;
        if (ctx.hasUI) {
          ctx.ui.notify("Auto-compaction completed", "info");
        }
      },
      onError: (error) => {
        autoCompactionInProgress = false;
        if (ctx.hasUI) {
          ctx.ui.notify(`Auto-compaction failed: ${error.message}`, "error");
        }
      },
    });
  });

  pi.on("session_before_compact", async (event, ctx) => {
    const { preparation, signal } = event;
    const {
      messagesToSummarize,
      turnPrefixMessages,
      tokensBefore,
      firstKeptEntryId,
      previousSummary,
    } = preparation;

    // Resolve the configured model
    const model = ctx.modelRegistry.find(
      compactionConfig!.provider,
      compactionConfig!.model,
    );
    if (!model) {
      ctx.ui.notify(
        `Compaction model "${compactionConfig!.provider}/${compactionConfig!.model}" not found, using default`,
        "warning",
      );
      return;
    }

    // Resolve request auth for the summarization model
    const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
    if (!auth.ok) {
      ctx.ui.notify(
        `Compaction auth failed: ${auth.error}, using default compaction`,
        "warning",
      );
      return;
    }
    if (!auth.apiKey) {
      ctx.ui.notify(
        `No API key for ${compactionConfig!.provider}, using default compaction`,
        "warning",
      );
      return;
    }

    // Combine all messages for summary
    const allMessages = [...messagesToSummarize, ...turnPrefixMessages];

    ctx.ui.notify(
      `Compacting ${tokensBefore.toLocaleString()} tokens with ${model.id}...`,
      "info",
    );

    // Convert messages to readable text format
    const conversationText = serializeConversation(convertToLlm(allMessages));

    // Include previous summary context if available
    const previousContext = previousSummary
      ? `\n\nPrevious session summary for context:\n${previousSummary}`
      : "";

    // Build messages that ask for a comprehensive summary
    const summaryMessages = [
      {
        role: "user" as const,
        content: [
          {
            type: "text" as const,
            text: `You are a session compaction expert for an AI coding agent. Your goal is to create a "Checkpoint Summary" that enables another agent to resume work with zero loss of technical context.

Include the following in your summary:${previousContext}

### 1. Primary Objective
- Clear statement of the current goal and any background context provided by the user.

### 2. Technical Decisions & Findings
- Key architectural choices or logic implemented.
- Critical findings from codebase research or documentation (e.g., "Library X doesn't support Y").

### 3. Execution History
- **Commands**: List specific shell commands used (e.g., git, nix, npm) and their results if they changed state or provided critical info.
- **Files**: List files modified or created. Be specific about what was changed in each.

### 4. Current Progress & State
- What is finished and verified?
- What is currently being worked on?
- Precise "in-flight" state: Are there open files with unsaved/unverified changes? Is there a failing test?

### 5. Blockers & Open Questions
- Any issues encountered that weren't resolved.
- Things the user needs to clarify.

### 6. Next Actions
- The immediate next 2-3 steps to continue the implementation.

**Constraint**: Be technical, dense, and precise. Prefer code snippets, paths, and exact error messages over vague descriptions. The summary replaces the entire history; if it's not here, it's lost.

Format the summary as structured markdown with clear sections.

<conversation>
${conversationText}
</conversation>`,
          },
        ],
        timestamp: Date.now(),
      },
    ];

    try {
      // Pass signal to honor abort requests
      const response = await complete(
        model,
        { messages: summaryMessages },
        {
          apiKey: auth.apiKey,
          headers: auth.headers,
          maxTokens: compactionConfig!.maxTokens ?? model.maxTokens,
          signal,
        },
      );

      const summary = response.content
        .filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");

      if (!summary.trim()) {
        if (!signal.aborted) {
          ctx.ui.notify(
            "Compaction summary was empty, using default",
            "warning",
          );
        }
        return;
      }

      // Return compaction content
      return {
        compaction: {
          summary,
          firstKeptEntryId,
          tokensBefore,
        },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      ctx.ui.notify(`Compaction failed: ${message}, using default`, "error");
      // Fall back to default compaction on error
      return;
    }
  });
}
