#!/bin/sh
#
# ~/.profile
#

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=vi

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.data
export XDG_STATE_HOME=$HOME/.state

PATH=/usr/local/sbin:$PATH
PATH=/usr/local/bin:$PATH
PATH=$HOME/.local/bin:$PATH
PATH=$HOME/.local/var/npm/bin:$PATH

#
# Rust
#

export RUST_SRC_PATH=$HOME/.local/src/rust/current/src/
PATH=$HOME/.cargo/bin:$PATH

#
# Erlang
#

PATH=$HOME/.cache/rebar3/bin:$PATH

#
# Golang
#

export GOPATH=$HOME/Dev/go/
PATH=$HOME/Dev/go/bin:$PATH

#
# Platform-specific
#

if [ "$(uname)" = "Darwin" ]; then
    PATH=/usr/local/opt/gpg-agent/bin:$PATH
    PATH=/usr/local/opt/node@8/bin:$PATH

    if hash brew 2>/dev/null; then
        export HOMEBREW_NO_ANALYTICS=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
        export OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib
    fi

    if [ -f /usr/libexec/java_home ]; then
        JAVA_HOME=$(/usr/libexec/java_home)
        export JAVA_HOME
    fi

    if [ -d /Applications/mpv.app/Contents/MacOS ]; then
        PATH=/Applications/mpv.app/Contents/MacOS:$PATH
    fi

    if [ -d "/Applications/VMware Fusion.app" ]; then
        export VAGRANT_VMWARE_CLONE_DIRECTORY="$HOME/Virtual Machines"
    fi
fi

if hash keychain 2>/dev/null; then
    eval "$(keychain --eval --agents ssh,gpg --quiet)"
fi

export PATH
