---
- name: initialize brew taps
  homebrew_tap: tap={{brew_taps}} state=present
  when: brew_taps

- name: install java
  homebrew_cask: name=java state=present

- name: install homebrew packages
  homebrew:
    name: "{{brew_packages}}"
    state: present
  when: brew_packages

- name: initialize cask taps
  homebrew_tap: tap={{cask_taps}} state=present
  when: cask_taps

- name: install cask packages
  homebrew_cask: name={{cask_packages}} state=present
  when: cask_packages

- name: prepare sudoers directory
  file: path=/etc/sudoers.d state=directory recurse=yes

- name: adding sudoers configurations
  become: yes
  copy:
    src: "sudoers/{{item}}"
    dest: "/etc/sudoers.d/{{item}}"
  with_items:
    - 01_dnscrypt
    - 01_unbound
    - 01_vagrant
