---
- name: initialize brew taps
  homebrew_tap: tap={{brew_taps}} state=present

- name: install java
  homebrew_cask: name=java state=present

- name: install homebrew packages
  homebrew:
    name: "{{brew_packages}}"
    install_options: build-from-source
    state: present

- name: prepare sudoers directory
  file: path=/etc/sudoers.d state=directory recurse=yes

- name: adding vagrant sudoers
  become: yes
  copy:
    src: "vagrant/01_vagrant_{{ansible_os_family|lower}}"
    dest: /etc/sudoers.d/01_vagrant
