---
## Setup FreeBSD ports
##

- name: fetch freebsd source
  become: yes
  shell: >
    fetch -o - "ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/$(freebsd-version -k | sed 's/\-p.*$//g')/src.txz" |
    tar -C / -xvzf -
  args:
    warn: no
    creates: /usr/src/Makefile

- name: ensure configuration directories
  become: yes
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /usr/local/etc/synth
    - /root/.ccache

- name: copy build configurations
  become: yes
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: base/src.conf, dest: /etc/src.conf }
    - { src: ccache/ccache.conf, dest: /root/.ccache/ccache.conf }
    - { src: synth/make.conf, dest: /usr/local/etc/synth/LiveSystem-make.conf }


## Install FreeBSD ports packages
##

- name: install ports packages via synth
  become: yes
  synth:
    name: "{{ports_packages}}"
    state: present
  when: ports_packages


## Configure system
##

- name: configure sysctl
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item.key}}={{item.value}}"
    regexp: "^(# ?)?{{item.key}}="
  with_items:
    - { key: "security.bsd.see_other_uids", value: "0" }
    - { key: "kern.maxfiles", value: "5242880" }
    - { key: "kern.maxfilesperproc", value: "524288" }

- name: configure periodic logging
  become: yes
  lineinfile:
    dest: /etc/periodic.conf
    line: "{{item}}"
    create: yes
    state: present
  with_items:
    - daily_output="/var/log/daily.log"
    - weekly_output="/var/log/weekly.log"
    - monthly_output="/var/log/monthly.log"


## Configure system for VirtualBox
## See also: https://www.freebsd.org/doc/handbook/virtualization-host-virtualbox.html
##

- name: configure virtualbox kernel module
  become: yes
  lineinfile:
    dest: /boot/loader.conf
    line: vboxdrv_load="YES"
    state: present
    create: yes

- name: enable vboxnet service
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: vboxnet_enable="YES"
    state: present

- name: configure virtualbox network module
  become: yes
  blockinfile:
    path: /etc/devfs.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      own vboxnetctl root:vboxusers
      perm vboxnetctl 0600

- name: add {{ansible_user_id}} to vboxusers group
  become: yes
  user:
    name: "{{ansible_user_id}}"
    groups: vboxusers
    append: yes


## Setup terminfo
##

- name: setup 24-bits terminfo
  become: yes
  shell: |
    if ! infocmp xterm-24bits >/dev/null 2>&1; then
      tic -s -x {{ansible_env.HOME}}/.dotfiles/_var/terminfo-24bit.src
      ( \
        printf "\n"
        printf "# These entries do not have 24-bit support, they are added\n"
        printf "# so those built against system termcap do not fail.\n"
        printf "# --"
        tic -C -K -s -x {{ansible_env.HOME}}/.dotfiles/_var/terminfo-24bit.src
      ) >> /usr/share/misc/termcap
      cd /usr/share/misc
      cap_mkdb termcap
      exit 9
    fi
  register: terminfo_register
  failed_when: terminfo_register.rc != 0 and terminfo_register.rc != 9
  changed_when: terminfo_register.rc == 9
