---
- name: fetch freebsd source
  become: yes
  shell: >
    fetch -o - "ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/$(freebsd-version -k | sed 's/\-p.*$//g')/src.txz" |
    tar -C / -xvzf -
  args:
    warn: no
    creates: /usr/src/Makefile

- name: install ports packages via synth
  become: yes
  command: /usr/local/bin/synth install {{ports_packages|join(" ")}}
  register: synth_install
  changed_when: synth_install.stdout.find("The most recent version of packages are already installed") == -1

# setup sysctl

- name: configure sysctl
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item.key}}={{item.value}}"
    regexp: "^(# ?)?{{item.key}}="
  with_items:
    - { key: "security.bsd.see_other_uids", value: "0" }
    - { key: "kern.maxfiles", value: "5242880" }
    - { key: "kern.maxfilesperproc", value: "524288" }
    - { key: "vfs.usermount", value: "1" }

# setup logging

- name: configure periodic logging
  become: yes
  lineinfile:
    dest: /etc/periodic.conf
    line: "{{item}}"
    create: yes
    state: present
  with_items:
    - daily_output="/var/log/daily.log"
    - weekly_output="/var/log/weekly.log"
    - monthly_output="/var/log/monthly.log"

# setup fuse

- name: configure fuse kernel module
  become: yes
  lineinfile:
    dest: /boot/loader.conf
    line: fuse_load="YES"
    state: present
    create: yes

- name: add {{ansible_user_id}} to operator group
  become: yes
  user:
    name: "{{ansible_user_id}}"
    groups: operator
    append: yes

# setup virtualbox kernel modules and permissions
# see also: https://www.freebsd.org/doc/handbook/virtualization-host-virtualbox.html

- name: configure virtualbox kernel module
  become: yes
  lineinfile:
    dest: /boot/loader.conf
    line: vboxdrv_load="YES"
    state: present
    create: yes

- name: enable vboxnet service
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: vboxnet_enable="YES"
    state: present

- name: configure virtualbox network module
  become: yes
  blockinfile:
    path: /etc/devfs.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      own vboxnetctl root:vboxusers
      perm vboxnetctl 0600

- name: add {{ansible_user_id}} to vboxusers group
  become: yes
  user:
    name: "{{ansible_user_id}}"
    groups: vboxusers
    append: yes
