---
## Setup FreeBSD ports
##

- name: fetch freebsd source
  become: yes
  shell: >
    fetch -o - "ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/$(freebsd-version -k | sed 's/\-p.*$//g')/src.txz" |
    tar -C / -xvzf -
  args:
    warn: no
    creates: /usr/src/Makefile

- name: ensure configuration directories
  become: yes
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /usr/local/etc/synth
    - /root/.ccache

- name: copy build configurations
  become: yes
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: base/src.conf, dest: /etc/src.conf }
    - { src: ccache/ccache.conf, dest: /root/.ccache/ccache.conf }
    - { src: synth/make.conf, dest: /usr/local/etc/synth/LiveSystem-make.conf }


## Install FreeBSD ports packages
##

- name: install ports packages via synth
  become: yes
  synth:
    name: "{{ports_packages}}"
    state: present
  when: ports_packages


## Configure system
##

- name: configure bootloader
  become: yes
  lineinfile:
    path: /boot/loader.conf
    line: "{{item.key}}={{item.value}}"
    regexp: "^(# ?)?{{item.key}}="
  with_items:
    - { key: "cc_htcp_load", value: "YES" }
    - { key: "fuse_load", value: "YES" }
    - { key: "kern.racct.enable", value: "1" }

- name: configure sysctl
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item.key}}={{item.value}}"
    regexp: "^(# ?)?{{item.key}}="
  with_items:
    - { key: "kern.maxfiles", value: "5242880" }
    - { key: "kern.maxfilesperproc", value: "524288" }
    - { key: "net.inet.tcp.cc.algorithm", value: "htcp" }
    - { key: "net.link.tap.up_on_open", value: "1" }
    - { key: "security.bsd.see_other_uids", value: "0" }
    - { key: "vfs.usermount", value: "1" }

- name: configure periodic logging
  become: yes
  lineinfile:
    dest: /etc/periodic.conf
    line: "{{item}}"
    create: yes
    state: present
  with_items:
    - daily_output="/var/log/daily.log"
    - weekly_output="/var/log/weekly.log"
    - monthly_output="/var/log/monthly.log"


## Configure user
##

- name: add current user to operator group
  become: yes
  user:
    name: "{{ansible_user_id}}"
    groups: operator
    append: yes
