---
## Include platform-specific playbooks
##

- include_vars: "{{ansible_os_family|lower}}.yml"
  tags:
    - always

- include_tasks: "{{ansible_os_family|lower}}.yml"


## Install cross-platform packages managed by asdf
##

- name: install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{asdf_path}}"
    version: "v{{asdf_version}}"
  tags:
    - asdf

- name: ensure asdf plugin directory
  file:
    path: "{{asdf_path}}/plugins"
    state: directory
    recurse: yes
  tags:
    - asdf

- import_tasks: "asdf/erlang.yml"
  tags:
    - asdf
    - erlang

- import_tasks: "asdf/elixir.yml"
  tags:
    - asdf
    - elixir

- import_tasks: "asdf/golang.yml"
  tags:
    - asdf
    - golang

- import_tasks: "asdf/nim.yml"
  tags:
    - asdf
    - nim

- import_tasks: "asdf/python3.yml"
  tags:
    - asdf
    - python3

- import_tasks: "asdf/ruby.yml"
  tags:
    - asdf
    - ruby


## Install cross-platform packages
##

- import_tasks: "pkgs/haskell.yml"
  tags:
    - haskell

- import_tasks: "pkgs/nodejs.yml"
  tags:
    - nodejs

- import_tasks: "pkgs/rust.yml"
  tags:
    - rust


## Setup links
##

- name: prepare dot directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items: "{{dots}}"

- name: link files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{dots_links}}"


## Setup user shells
##

- name: ensure bash is in available shells
  become: yes
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/bash

- name: set user default shell
  become: yes
  user:
    name: "{{ansible_user_id}}"
    shell: /usr/local/bin/bash
