---
- name: import aur gpg key
  shell: >-
    gpg --list-keys {{item}} 2>/dev/null ||
      curl -s "https://pgp.mit.edu/pks/lookup?op=get&search=0x{{item}}" |
      gpg --import
  register: import_aur_key
  changed_when: import_aur_key.stdout.find('imported') > 0
  with_items: "{{aur_keys}}"

- name: update pacaur
  pacaur: update_cache=yes
  notify:
    - upgrade pacaur packages

- name: install pacaur packages
  pacaur: name={{item}} state=present
  with_items: "{{aur_packages}}"
