---
- name: check cower installation
  shell: pacman -Q |grep cower |head -n1
  register: check_cower
  changed_when: not check_cower.stdout

- name: download tarball for cower
  get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/cower.tar.gz"
    dest: /tmp/
  register: download_cower
  when: not check_cower.stdout

- name: extract tarball for cower
  unarchive:
    src: "{{download_cower.dest}}"
    dest: /tmp
  register: extract_cower
  when: download_cower.changed

- name: import gpg key for cower
  shell:
    gpg --list-keys 1EB2638FF56C0C53 2>/dev/null ||
      curl -s "https://pgp.mit.edu/pks/lookup?op=get&search=0x1EB2638FF56C0C53" |
      gpg --import
  register: import_cower_key
  changed_when: import_cower_key.stdout.find('imported') > 0
  when: not check_cower.stdout

- name: build package for cower
  command: >-
    makepkg --noconfirm --noprogressbar -mfs
    chdir=/tmp/cower
  when: not check_cower.stdout

- name: install cower
  become: yes
  shell: >-
    pacman --noconfirm --noprogressbar --needed -U *.pkg.tar.xz
    chdir=/tmp/cower
  register: install_cower
  changed_when: install_cower.stdout.find('there is nothing to do') == -1
  when: not check_cower.stdout
