#!/bin/sh
#
# ~/.profile
#
umask 077

LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
EDITOR="vi"
VISUAL="emacs"

export LC_ALL
export LANG
export EDITOR
export VISUAL

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.data
XDG_STATE_HOME=$HOME/.state

export XDG_CONFIG_HOME
export XDG_CACHE_HOME
export XDG_DATA_HOME
export XDG_STATE_HOME

appendpath() {
    case ":$PATH:" in
        *:"$1":*)
            ;;

        * )
            PATH="${PATH:+$PATH:}$1"
            ;;
    esac
}

GOPATH=$HOME/Dev/go
export GOPATH

# Note: leading colon to append to default MANPATH
MANPATH=:$HOME/.local/man
export MANPATH

RUST_SRC_PATH="$HOME/.local/lib/rustlib/src/rust/src"
export RUST_SRC_PATH

appendpath "$HOME/.local/bin"
appendpath "$HOME/.cabal/bin"
appendpath "$HOME/.cargo/bin"
appendpath "$GOPATH/bin"


## Platform-specific
##

case "$(uname)" in
    Darwin )
        appendpath /opt/local/bin

        if [ -f /usr/libexec/java_home ]; then
            JAVA_HOME=$(/usr/libexec/java_home)
            export JAVA_HOME
        fi

        for pypath in "$HOME"/Library/Python/?.?/bin; do
            if [ -d "$pypath" ]; then
                appendpath "$pypath"
            fi
        done
        ;;
esac


## Local
##

if [ -d "$HOME/.cache/rebar3/bin" ]; then
    appendpath "$HOME/.cache/rebar3/bin"
fi

for rbpath in "$HOME"/.gem/ruby/?.?/bin; do
    if [ -d "$rbpath" ]; then
        appendpath "$rbpath"
    fi
done


## GPG agent
##

if command -v gpgconf >/dev/null; then
    unset SSH_AGENT_PID

    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
        SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
        export SSH_AUTH_SOCK
    fi

    GPG_TTY=$(tty)
    export GPG_TTY
fi


## Desktop
##

case "${XDG_SESSION_TYPE}" in
    wayland | x11 ) [ -f "$HOME/.desktoprc" ] && . "$HOME/.desktoprc";;
    * ) ;;
esac


## Finalizing
##

ENV="$HOME/.kshrc"

export ENV
export PATH
unset appendpath
