#!/bin/sh
#
# ~/.profile
#

LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
EDITOR="vi"
VISUAL="emacs"

export LC_ALL
export LANG
export EDITOR
export VISUAL

XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.state

export XDG_CONFIG_HOME
export XDG_CACHE_HOME
export XDG_DATA_HOME
export XDG_STATE_HOME


## Binary wrappers
## alias doesn't work as login .profile
##

PATH=$HOME/.dotfiles/libexec/fakebin:$PATH


## GPG agent
##

if command -v gpgconf >/dev/null; then
    unset SSH_AGENT_PID

    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
        SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
        export SSH_AUTH_SOCK
    fi
fi


## Emacs
##

if command -v emacs >/dev/null; then
    EDITOR="emacs"
    export EDITOR
fi


## Finalizing
##

ENV="$HOME/.kshrc"

export ENV
export PATH
