set nocompatible                  " disable vi-compatibility
set backspace=indent,eol,start    " allow backspace over everything
set nobackup                      " everything is already in VCS
set history=50                    " keep 50 lines of command line history
set ruler                         " show the cursor position all the time
set showcmd                       " display incomplete commands
set incsearch                     " do incremental searching
set hlsearch                      " highlight matched searchs
set autoindent                    " always enable auto indentation
set expandtab                     " insert spaces instead of tab
set tabstop=4                     " number of spaces for each tab
set shiftwidth=4                  " for autoindent
set softtabstop=4                 " make backspace jump to previous stop
set smartindent                   " auto detect when to insert indentation

set wildmenu                      " show completion on top of status line
set wildmode=longest,full         " complete longest, then show completions
set cursorline                    " highlight current line
set laststatus=2                  " always show the status line

set guioptions-=T

" Fix comment indentation
set cindent
set cinkeys=0{,0},!^F,o,O,e

syntax on                              " always color terminal anyway
au BufNewFile,BufRead *.j setf objj    " syntax highlight for Objective-J
au BufNewFile,BufRead *.fish setf fish "syntax highlight for Fish

autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" Navigation
nmap <C-p> :tabprevious<cr>
nmap <C-n> :tabnext<cr>

" Omni completion
set ofu=syntaxcomplete#Complete

" Filetype-specific settings
autocmd FileType python setlocal smartindent
  \ cinwords=if,elif,else,for,while,try,except,finally,def,class

autocmd FileType clojure,ruby,cucumber,eruby,scss setlocal shiftwidth=2
autocmd FileType clojure,ruby,cucumber,eruby,scss setlocal tabstop=2
autocmd FileType clojure,ruby,cucumber,eruby,scss setlocal softtabstop=2
autocmd FileType yaml,html,htmldjango,haml,sass setlocal shiftwidth=2
autocmd FileType yaml,html,htmldjango,haml,sass setlocal tabstop=2
autocmd FileType yaml,html,htmldjango,haml,sass setlocal softtabstop=2

" Personalization
colorscheme molokai
set textwidth=0

if exists("&colorcolumn")
  set colorcolumn=79
endif

" Display TextMate-like symbol for tabs and \n
set list
set listchars=tab:▸\ ,eol:¬

" These extras are pretty much unneeded when I'm not coding
if has("gui_running")

  " Default font for Linux, Mac, Windows
  set guifont=Inconsolata-dz:h12,Monospace,Menlo,Consolas
  autocmd FileType html setlocal colorcolumn=0

  " Initial line size and line numbers
  set number
  set lines=50

endif

" vim:ft=vim
