set nocompatible                  " disable vi-compatibility
set backspace=indent,eol,start    " allow backspace over everything
set nobackup                      " everything is already in VCS
set history=50                    " keep 50 lines of command line history
set ruler                         " show the cursor position all the time
set showcmd                       " display incomplete commands
set incsearch                     " do incremental searching
set hlsearch                      " highlight matched searchs
set autoindent                    " always enable auto indentation
set expandtab                     " insert spaces instead of tab
set tabstop=4                     " number of spaces for each tab
set shiftwidth=4                  " for autoindent
set softtabstop=4                 " make backspace jump to previous stop
set smartindent                   " auto detect when to insert indentation

set wildmenu                      " show completion on top of status line
set wildmode=longest,full         " complete longest, then show completions
set cursorline                    " highlight current line
set laststatus=2                  " always show the status line
set shell=/bin/bash               " use POSIX-complaint shell

set guioptions-=T

" Fix comment indentation
set cindent
set cinkeys=0{,0},!^F,o,O,e

" Syntax highlight
syntax on                              " always color terminal anyway
au BufNewFile,BufRead *.j setf objj    " syntax highlight for Objective-J
au BufNewFile,BufRead *.fish setf fish " syntax highlight for Fish
au BufNewFile,BufRead Vagrantfile setf ruby " syntax highlight for Vagrant

autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" Navigation
nmap <C-p> :tabprevious<cr>
nmap <C-n> :tabnext<cr>

" Omni completion
set ofu=syntaxcomplete#Complete

" Filetype-specific settings
autocmd FileType python setlocal smartindent
  \ cinwords=if,elif,else,for,while,try,except,finally,def,class

" Shorttabs (2 tabs instead of default 4)
let s:shorttabs = [
  \ "clojure",
  \ "cucumber",
  \ "eruby",
  \ "haml",
  \ "ruby",
  \ "sass",
  \ "scss",
  \ "vim",
  \ "yaml"
  \ ]
autocmd FileType * if index(s:shorttabs, &ft) > 0 | setlocal shiftwidth=2
autocmd FileType * if index(s:shorttabs, &ft) > 0 | setlocal tabstop=2
autocmd FileType * if index(s:shorttabs, &ft) > 0 | setlocal softtabstop=2

" Personalization
colorscheme molokai
set textwidth=0

if exists("&colorcolumn")
  set colorcolumn=79
endif

" Display TextMate-like symbol for tabs and \n
set list
set listchars=tab:▸\ ,eol:¬

" Remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Initialize Vundle if submodule exists.
if isdirectory(expand("~/.dotfiles/vim/bundle/vundle"))

  filetype off
  set rtp+=~/.dotfiles/vim/bundle/vundle/
  call vundle#rc()

  " Let Vundle manage Vundle
  Bundle 'gmarik/vundle'

  " Bundles!
  Bundle 'tpope/vim-fugitive'
  Bundle 'rstacruz/sparkup'
  Bundle 'wincent/Command-T'
  Bundle 'bling/vim-airline'

  " Required by Vundle
  filetype plugin indent on

endif

" These extras are pretty much unneeded when I'm not coding
if has("gui_running")

  " Default font for Linux, Mac, Windows
  set guifont+=Inconsolata-dz\ for\ Powerline:h12
  set guifont+=Inconsolata-dz:h12
  set guifont+=Monospace
  set guifont+=Menlo
  set guifont+=Consolas
  autocmd FileType html setlocal colorcolumn=0

  " Initial line size and line numbers
  set number
  set lines=50

  " Airline
  let g:airline_powerline_fonts=1

endif

" vim:ft=vim
