---
- name: prepare elm directory
  file:
    path: ~/.local/src/elm
    state: directory

- name: clone elm source
  git:
    repo: "https://github.com/{{item.repo}}"
    dest: "~/.local/src/elm/{{item.dest}}"
    version: "{{elm_version}}"
  with_items:
    - { repo: "elm/compiler", dest: "elm-compiler" }
    - { repo: "elm-lang/elm-package", dest: "elm-package" }
    - { repo: "elm-lang/elm-make", dest: "elm-make" }
    - { repo: "elm-lang/elm-reactor", dest: "elm-reactor" }
    - { repo: "elm-lang/elm-repl", dest: "elm-repl" }
  register: elm_clone

- name: initialize stack for elm
  command: stack init --resolver ghc-7.10.2
  args:
    creates: ~/.local/src/elm/stack.yaml
    chdir: ~/.local/src/elm

- name: patch dependencies in stack.yaml for elm
  replace:
    path: ~/.local/src/elm/stack.yaml
    regexp: "^- {{item.pkg}}-(.*)$"
    replace: "- {{item.pkg}}-{{item.version}}"
  with_items:
    - { pkg: basement, version: "0.0.7" }
    - { pkg: foundation, version: "0.0.20" }
    - { pkg: fsnotify, version: "0.2.1.2" }

- name: install elm
  command: stack install elm-compiler elm-package elm-make elm-repl
  args:
    chdir: ~/.local/src/elm
  when: elm_clone.changed

- name: install elm-reactor
  command: stack install elm-reactor
  args:
    chdir: ~/.local/src/elm
  when: elm_clone.changed
