---
- name: ensure local directory
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items:
    - ~/.local/bin
    - ~/.local/src

- name: clone kubectx
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: ~/.local/src/kubectx
    version: "{{kubectx_version}}"

- name: link kubectx and kubens
  file:
    src: "~/.local/src/kubectx/{{item}}"
    path: "~/.local/bin/{{item}}"
    state: link
    force: yes
  with_items:
    - kubectx
    - kubens
