---
## NodeJS
##

- name: ensure nodejs user directory
  file:
    path: ~/.local/var/npm
    state: directory

- name: set npm prefix
  lineinfile:
    dest: ~/.npmrc
    line: "prefix={{ansible_env.HOME}}/.local/var/npm"
    state: present
    create: yes


## NodeJS packages
##

- name: install nodejs packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
  environment:
    PATH: "{{env_path}}"
  with_items: "{{nodejs_packages}}"
  when: nodejs_packages
