---
## Rust
##

- name: install rust
  shell: >
    curl https://sh.rustup.rs -sSf |
    sh -s - -y --no-modify-path
  args:
    warn: no
    creates: ~/.cargo/bin/rustup

- name: update rust version
  command: rustup update
  register: update_rust
  changed_when: update_rust.stdout.find("unchanged") == -1
  environment:
    PATH: "{{env_path}}"


## Rust components
##

- name: add rust components
  command: rustup component add "{{item}}"
  register: fetch_rust_component
  changed_when: fetch_rust_component.stderr.find("is up to date") == -1
  environment:
    PATH: "{{env_path}}"
  with_items: "{{rust_components}}"
  when: rust_components


## Rust packages
##

- name: install rust packages
  command: "cargo install {{item.name}} {{item.flags}}"
  args:
    creates: "~/.cargo/bin/{{item.binary}}"
  environment:
    PATH: "{{env_path}}"
  with_items: "{{rust_cargo_packages}}"
  when: rust_cargo_packages
