/**
 * Smart Compact Extension for Pi Coding Agent
 *
 * Uses a configurable model for session compaction instead of the default model.
 * The provider/model pair is read from custom.json generated by Nix config.
 * Falls back to default compaction if the configured model is unavailable.
 */

import { complete } from "@mariozechner/pi-ai";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import {
  convertToLlm,
  serializeConversation,
} from "@mariozechner/pi-coding-agent";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

// Load compaction model config at extension load time
// Extensions are at ~/.pi/agent/extensions/home-manager/extensions/
// custom.json is at ~/.pi/agent/custom.json
const configPath = join(import.meta.dirname, "../../../custom.json");

interface CompactionModelConfig {
  provider: string;
  model: string;
}

interface CustomConfig {
  compactionModel?: CompactionModelConfig | null;
}

let compactionConfig: CompactionModelConfig | null = null;

try {
  if (existsSync(configPath)) {
    const customConfig: CustomConfig = JSON.parse(
      readFileSync(configPath, "utf-8"),
    );
    if (customConfig.compactionModel) {
      compactionConfig = customConfig.compactionModel;
    }
  }
} catch {
  // Config missing or invalid - extension will be a no-op
}

export default function (pi: ExtensionAPI) {
  // Skip if no config
  if (!compactionConfig) {
    return;
  }

  pi.on("session_before_compact", async (event, ctx) => {
    const { preparation, signal } = event;
    const {
      messagesToSummarize,
      turnPrefixMessages,
      tokensBefore,
      firstKeptEntryId,
      previousSummary,
    } = preparation;

    // Resolve the configured model
    const model = ctx.modelRegistry.find(
      compactionConfig!.provider,
      compactionConfig!.model,
    );
    if (!model) {
      ctx.ui.notify(
        `Compaction model "${compactionConfig!.provider}/${compactionConfig!.model}" not found, using default`,
        "warning",
      );
      return;
    }

    // Get API key
    const apiKey = await ctx.modelRegistry.getApiKey(model);
    if (!apiKey) {
      ctx.ui.notify(
        `No API key for ${compactionConfig!.provider}, using default compaction`,
        "warning",
      );
      return;
    }

    // Combine all messages for summary
    const allMessages = [...messagesToSummarize, ...turnPrefixMessages];

    ctx.ui.notify(
      `Compacting ${tokensBefore.toLocaleString()} tokens with ${model.id}...`,
      "info",
    );

    // Convert messages to readable text format
    const conversationText = serializeConversation(convertToLlm(allMessages));

    // Include previous summary context if available
    const previousContext = previousSummary
      ? `\n\nPrevious session summary for context:\n${previousSummary}`
      : "";

    // Build messages that ask for a comprehensive summary
    const summaryMessages = [
      {
        role: "user" as const,
        content: [
          {
            type: "text" as const,
            text: `You are a conversation summarizer. Create a comprehensive summary of this conversation that captures:${previousContext}

1. The main goals and objectives discussed
2. Key decisions made and their rationale
3. Important code changes, file modifications, or technical details
4. Current state of any ongoing work
5. Any blockers, issues, or open questions
6. Next steps that were planned or suggested

Be thorough but concise. The summary will replace the ENTIRE conversation history, so include all information needed to continue the work effectively.

Format the summary as structured markdown with clear sections.

<conversation>
${conversationText}
</conversation>`,
          },
        ],
        timestamp: Date.now(),
      },
    ];

    try {
      // Pass signal to honor abort requests
      const response = await complete(
        model,
        { messages: summaryMessages },
        {
          apiKey,
          maxTokens: model.maxTokens,
          signal,
        },
      );

      const summary = response.content
        .filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");

      if (!summary.trim()) {
        if (!signal.aborted) {
          ctx.ui.notify(
            "Compaction summary was empty, using default",
            "warning",
          );
        }
        return;
      }

      // Return compaction content
      return {
        compaction: {
          summary,
          firstKeptEntryId,
          tokensBefore,
        },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      ctx.ui.notify(`Compaction failed: ${message}, using default`, "error");
      // Fall back to default compaction on error
      return;
    }
  });
}
