#!/usr/bin/env ksh
#
# ~/.kshrc
#

## Aliases
##

if command -v colorls >/dev/null; then
    alias ls="colorls -G"
elif ls --version 2>&1 |grep -qe "BusyBox" -e "GNU"; then
    alias ls="ls --color"
elif ls -G 2>&1; then
    alias ls="ls -G"
fi

alias ll='ls -lh'
alias la='ls -alh'
alias gpg='gpg2'
alias sshi='ssh -F /dev/null -o UserKnownHostsFile=/dev/null'

if command -v emacsclient >/dev/null; then
    alias emacs='$HOME/.dotfiles/bin/emacsclient'
    EDITOR="$HOME/.dotfiles/bin/emacsclient"
    export EDITOR
fi


## History
##

HISTFILE="$HOME/.ksh_history"
HISTSIZE=10000

export HISTFILE
export HISTSIZE


## GPG
##

if command -v gpg-connect-agent >/dev/null; then
    gpg-connect-agent updatestartuptty /bye >/dev/null
fi


## Prompt
##

case "$TERM" in
    xterm* | rxvt* ) PS1="\h \w \$ ";;
    screen* ) PS1="\w \$ ";;
    * ) PS1="\$ ";;
esac

export PS1
