#!/bin/bash

printf "\033[1;1m%-17s %-17s %s\033[0;0m\n" "AutomaticChecks" "AutomaticUpdate" "Bundle ID"
printf "%-8s %-8s %-8s %-8s\n" "Default" "User" "Default" "User"

installed_apps=$(system_profiler SPApplicationsDataType |sed -n 's/^ *Location: \/Applications\/\(.*\)/\1/p' |sort)
sparkle_check_key="SUEnableAutomaticChecks"
sparkle_update_key="SUAutomaticallyUpdate"

f_true="\033[0;32mtrue\033[0;0m"
f_false="\033[0;33mfalse\033[0;0m"
f_unknown="\033[1;30munset\033[0;0m"

while read -r app_relative_path; do
    app_path="/Applications/${app_relative_path}"
    sparkle_framework="${app_path}/Contents/Frameworks/Sparkle.framework"
    info_plist="${app_path}/Contents/Info.plist"

    if [ -f "${app_path}/Contents/_MASReceipt/receipt" ]; then
        continue
    fi

    if [ ! -d "${sparkle_framework}" ]; then
        continue
    fi

    app_bundle_id=$(defaults read "${info_plist}" "CFBundleIdentifier")
    sparkle_check_default=$(defaults read "${info_plist}" "${sparkle_check_key}" 2>/dev/null)
    sparkle_update_default=$(defaults read "${info_plist}" "${sparkle_update_key}" 2>/dev/null)
    sparkle_check_user=$(defaults read "${app_bundle_id}" "${sparkle_check_key}" 2>/dev/null)
    sparkle_update_user=$(defaults read "${app_bundle_id}" "${sparkle_update_key}" 2>/dev/null)

    case "${sparkle_check_default}" in
        1|YES|TRUE)
            sparkle_check_default="${f_true}"
            ;;
        0|NO|FALSE)
            sparkle_check_default="${f_false}"
            ;;
        *)
            sparkle_check_default="${f_unknown}"
            ;;
    esac

    case "${sparkle_update_default}" in
        1|YES|TRUE)
            sparkle_update_default="${f_true}"
            ;;
        0|NO|FALSE)
            sparkle_update_default="${f_false}"
            ;;
        *)
            sparkle_update_default="${f_unknown}"
            ;;
    esac

    case "${sparkle_check_user}" in
        1|YES|TRUE)
            sparkle_check_user="${f_true}"
            ;;
        0|NO|FALSE)
            sparkle_check_user="${f_false}"
            ;;
        *)
            sparkle_check_user="${f_unknown}"
    esac

    case "${sparkle_update_user}" in
        1|YES|TRUE)
            sparkle_update_user="${f_true}"
            ;;
        0|NO|FALSE)
            sparkle_update_user="${f_false}"
            ;;
        *)
            sparkle_update_user="${f_unknown}"
            ;;
    esac

    printf "%-21b %-21b %-21b %-21b \033[1;35m%s\033[0;0m\n" \
           "${sparkle_check_default}" "${sparkle_check_user}" \
           "${sparkle_update_default}" "${sparkle_update_user}" \
           "${app_bundle_id}"
done <<< "$installed_apps"
