---
- name: install unbound service
  homebrew: name=unbound state=latest
  notify:
    - unload unbound launchd service
    - load unbound launchd service

- name: ensure unbound directories
  become: yes
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
    owner: nobody
    group: nobody
  with_items:
    - /usr/local/svcs/unbound/etc
    - /usr/local/svcs/unbound/var

- name: update unbound configurations
  become: yes
  template:
    src: unbound/unbound.conf.j2
    dest: "/usr/local/svcs/unbound/etc/unbound.conf"
    owner: nobody
    group: nobody
  notify:
    - unload unbound launchd service
    - load unbound launchd service

- name: enable unbound service
  become: yes
  template:
    src: unbound/net.unbound.unbound.plist.j2
    dest: /Library/LaunchAgents/net.unbound.unbound.plist
  notify:
    - unload unbound launchd service
    - load unbound launchd service
