---
- name: enable user-env service
  template:
    src: user-env/th.in.grid.user-env.plist.j2
    dest: ~/Library/LaunchAgents/th.in.grid.user-env.plist
  notify:
    - unload user-env launchd service
    - load user-env launchd service
