---

# packages/archlinux/pacman

- name: upgrade pacman packages
  become: yes
  pacman: upgrade=yes

# packages/acrhlinux/aur_pacaur

- name: upgrade pacaur packages
  pacaur: upgrade=yes

# packages/darwin/brew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes
  ignore_errors: yes

# services/archlinux/docker

- name: restart docker systemd service
  systemd:
    name: "docker"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/mpd

- name: restart mpd systemd service
  systemd:
    name: "mpd"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/nfs

- name: restart nfs-server systemd service
  become: yes
  systemd:
    name: "nfs-server"
    daemon_reload: yes
    state: restarted

# services/archlinux/redshift

- name: restart redshift systemd service
  systemd:
    name: "redshift"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/unbound

- name: restart unbound systemd service
  become: yes
  systemd:
    name: "unbound"
    daemon_reload: yes
    state: restarted

# services/darwin/dnscrypt

- name: unload dnscrypt-proxy launchd service
  become: yes
  command: launchctl unload /Library/LaunchDaemons/com.github.jedisct1.dnscrypt-proxy.plist
  ignore_errors: yes

- name: load dnscrypt-proxy launchd service
  become: yes
  command: launchctl load /Library/LaunchDaemons/com.github.jedisct1.dnscrypt-proxy.plist
  ignore_errors: yes

# services/darwin/user-env

- name: unload user-env launchd service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.user-env.plist
  ignore_errors: yes

- name: load user-env launchd service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.user-env.plist
  ignore_errors: yes

# services/darwin/unbound

- name: unload unbound launchd service
  become: yes
  command: launchctl unload /Library/LaunchDaemons/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound launchd service
  become: yes
  command: launchctl load /Library/LaunchDaemons/net.unbound.unbound.plist
  ignore_errors: yes
