#!/usr/bin/env bash
#
# ~/.bashrc
#

[[ $- != *i* ]] && return
[[ -s /etc/bashrc ]] && source /etc/bashrc

if [ -d "$HOME/.rbenv" ]; then
    PATH=$HOME/.rbenv/bin:$PATH
    PATH=$HOME/.rbenv/shims:$PATH
    rbenv rehash &>/dev/null &disown
fi

if [ -d "$HOME/.pyenv" ]; then
    PATH=$HOME/.pyenv/bin:$PATH
    PATH=$HOME/.pyenv/shims:$PATH
    pyenv rehash &>/dev/null &disown
fi

[[ $- != *c* ]] && exec fish
