#!/bin/sh
#
# ~/.xprofile
#

# Key mappings
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

# Ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
killall ibus-daemon
ibus-daemon --daemonize --xim
