---
- name: ensure pf directory
  become: yes
  file:
    path: /etc/pf
    state: directory

- name: configure initial pf
  become: yes
  copy:
    src: pf/pf.conf
    dest: /etc/pf.conf
    force: no

- name: configure main pf configurations
  become: yes
  template:
    src: "pf/main.{{item}}.conf.j2"
    dest: "/etc/pf/main.{{item}}.conf"
  register: pf_include_config
  with_items:
    - filter
    - normalization
    - queue
    - translation

- name: register main pf configurations
  become: yes
  lineinfile:
    path: /etc/pf.conf
    insertbefore: "# {{item|upper}}: END"
    line: "include \"/etc/pf/main.{{item}}.conf\""
  with_items:
    - filter
    - normalization
    - queue
    - translation
  register: pf_config

- name: validate pf configurations
  become: yes
  command: pfctl -n -f /etc/pf.conf
  register: pf_validate
  when: pf_config.changed or pf_include_config.changed

- name: enable pf
  become: yes
  service:
    name: pf
    enabled: yes
    state: started

- name: reload pf
  become: yes
  command: pfctl -F all -f /etc/pf.conf
  when: pf_validate.changed

# setup pf anchor hooks

- name: configure pf anchor hook script
  become: yes
  copy:
    src: pf/devd_anchor.sh
    dest: /usr/local/libexec/local-pf-ifnet
    mode: 0755

- name: ensure devd directory
  become: yes
  file:
    path: /usr/local/etc/devd/
    state: directory

- name: configure pf anchor devd
  become: yes
  copy:
    src: pf/devd_anchor.conf
    dest: /usr/local/etc/devd/pf_ifnet.conf
  notify:
    - restart devd rc service
