---
## Configure ports
##

- name: enable ports periodic
  become: yes
  copy:
    dest: /usr/local/etc/periodic/daily/900.ports
    mode: 0755
    content: |
      #!/bin/sh
      exec /usr/sbin/portsnap auto
