---
clang_bin: /usr/local/libexec/ccache/clang

env_paths:
  - "{{ansible_env.HOME}}/.local/bin"
  - "{{ansible_env.HOME}}/.cargo/bin"
  - "{{asdf_shims}}"
  - "{{ansible_env.PATH}}"

env_path: "{{env_paths|join(\":\")}}"

pf_allowed_ports:
  - name: Allow ssh
    port: "22"
    proto: tcp

  - name: Allow mosh
    port: "60000:61000"
    proto: udp

pf_nat:
  - name: Bhyve VIMAGE NAT
    network: "10.100.10.1/24"

  - name: Iocage VIMAGE NAT
    network: "10.100.20.1/24"

pf_ext_if: ix0

fuse_ld: gold

gcc_bin: /usr/local/libexec/ccache/gcc

gcc_rpath: /usr/local/libexec/ccache/gcc

gxx_bin: /usr/local/libexec/ccache/g++

gmake_bin: gmake

ports_packages:
  - converters/base64
  - converters/cocot
  - databases/postgresql10-client
  - devel/autoconf
  - devel/binutils
  - devel/ccache
  - devel/cmake
  - devel/git
  - devel/git-lfs
  - devel/gmake
  - devel/hs-ShellCheck
  - devel/hub
  - devel/jsonnet
  - devel/leiningen
  - devel/mercurial@py27
  - dns/dnsmasq
  - editors/emacs@nox
  - editors/neovim
  - emulators/qemu-utils
  - ftp/curl
  - graphics/GraphicsMagick
  - graphics/graphviz
  - java/openjdk8-jre
  - lang/execline
  - lang/expect
  - lang/gcc
  - misc/compat8x
  - multimedia/ffmpeg
  - multimedia/rtmpdump
  - net-mgmt/ipcalc
  - net/google-cloud-sdk
  - net/mosh
  - net/socat
  - ports-mgmt/synth
  - security/ca_root_nss
  - security/git-crypt
  - security/gnupg
  - security/libressl
  - shells/zsh
  - sysutils/ansible@py36
  - sysutils/bhyve-firmware
  - sysutils/coreutils
  - sysutils/direnv
  - sysutils/duplicity@py27
  - sysutils/entr
  - sysutils/fswatch-mon
  - sysutils/fusefs-sshfs
  - sysutils/grub2-bhyve
  - sysutils/helm
  - sysutils/kubectl
  - sysutils/lsof
  - sysutils/moreutils
  - sysutils/packer
  - sysutils/password-store
  - sysutils/s6
  - sysutils/terraform
  - sysutils/tmux
  - sysutils/tree
  - sysutils/vm-bhyve
  - sysutils/zfstools
  - textproc/groff
  - textproc/hs-pandoc
  - textproc/jq
  - textproc/py-asciinema@py36
  - textproc/ripgrep
  - www/aria2
  - www/node8
  - www/npm-node8
  - www/w3m
  - www/youtube_dl
