---
- name: restart dnscrypt-proxy launchd service
  become: yes
  brew_services:
    name: dnscrypt-proxy
    state: restarted

- name: restart userenv launchd service
  shell: |
    launchctl unload ~/Library/LaunchAgents/th.in.grid.userenv.plist &&
    launchctl load ~/Library/LaunchAgents/th.in.grid.userenv.plist
  ignore_errors: yes

- name: restart devd rc service
  become: yes
  service:
    name: devd
    state: restarted

- name: restart openntpd rc service
  become: yes
  service:
    name: openntpd
    state: restarted
