---
- name: restart dnscrypt-proxy launchd service
  become: yes
  shell: |
    launchctl unload /Library/LaunchDaemons/com.github.jedisct1.dnscrypt-proxy.plist &&
    launchctl load /Library/LaunchDaemons/com.github.jedisct1.dnscrypt-proxy.plist
  ignore_errors: yes

- name: restart user-env launchd service
  shell: |
    launchctl unload ~/Library/LaunchAgents/th.in.grid.user-env.plist &&
    launchctl load ~/Library/LaunchAgents/th.in.grid.user-env.plist
  ignore_errors: yes

- name: restart unbound launchd service
  become: yes
  shell: |
    launchctl unload /Library/LaunchDaemons/net.unbound.unbound.plist &&
    launchctl load /Library/LaunchDaemons/net.unbound.unbound.plist
  ignore_errors: yes

- name: restart zerotier-one launchd service
  become: yes
  shell: |
    launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist &&
    launchctl load /Library/LaunchDaemons/com.zerotier.one.plist
  ignore_errors: yes

- name: restart ntpd rc service
  become: yes
  service: name=ntpd enabled=yes state=restarted

- name: restart zerotier rc service
  become: yes
  service: name=zerotier enabled=yes state=restarted
