---
- name: install haskell plugin via asdf
  git:
    repo: https://github.com/vic/asdf-haskell.git
    dest: ~/.asdf/plugins/haskell

- name: install haskell {{haskell_version}} via asdf
  command: ~/.asdf/bin/asdf install haskell {{haskell_version}}
  args:
    creates: ~/.asdf/installs/haskell/{{haskell_version}}

- name: set haskell {{haskell_version}} as default
  command: ~/.asdf/bin/asdf global haskell {{haskell_version}}
  changed_when: false

- name: install haskell stack packages
  command: ~/.asdf/installs/haskell/{{haskell_version}}/bin/stack install {{item.name}}
  args:
    creates: ~/.asdf/installs/haskell/{{haskell_version}}/bin/{{item.binary}}
  with_items: "{{haskell_stack_packages}}"
  environment:
    PATH: "{{ansible_env.HOME}}/.asdf/installs/haskell/{{haskell_version}}/bin:{{ansible_env.PATH}}"

- name: update haskell {{haskell_version}} shims
  command: ~/.asdf/bin/asdf reshim haskell
  changed_when: false
