---
- name: install haskell plugin via asdf
  git:
    repo: https://github.com/vic/asdf-haskell.git
    dest: ~/.asdf/plugins/haskell

- name: install haskell {{haskell_version}} via asdf
  command: ~/.asdf/bin/asdf install haskell {{haskell_version}}
  args:
    creates: ~/.asdf/installs/haskell/{{haskell_version}}

- name: set haskell {{haskell_version}} as default
  command: ~/.asdf/bin/asdf global haskell {{haskell_version}}
  changed_when: false

- name: update haskell {{haskell_version}} shims
  command: ~/.asdf/bin/asdf reshim haskell
  changed_when: false
