---
- name: ensure nodejs keyring directory
  file:
    path: ~/.asdf/keyrings/nodejs
    mode: 0700
    state: directory

- name: install nodejs plugin via asdf
  git:
    repo: https://github.com/asdf-vm/asdf-nodejs.git
    dest: ~/.asdf/plugins/nodejs

- name: import nodejs release team keyring
  command: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  args:
    creates: ~/.asdf/keyrings/nodejs/trustdb.gpg
  environment:
    GNUPGHOME: "{{ansible_env.HOME}}/.asdf/keyrings/nodejs"

- name: install nodejs {{nodejs_version}} via asdf
  command: ~/.asdf/bin/asdf install nodejs {{nodejs_version}}
  args:
    creates: ~/.asdf/installs/nodejs/{{nodejs_version}}
  environment:
    GNUPGHOME: "{{ansible_env.HOME}}/.asdf/keyrings/nodejs"

- name: set nodejs {{nodejs_version}} as default
  command: ~/.asdf/bin/asdf global nodejs {{nodejs_version}}
  changed_when: false

- name: install nodejs packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
    executable: ~/.asdf/installs/nodejs/{{nodejs_version}}/bin/npm
  with_items: "{{nodejs_packages}}"
  environment:
    PATH: "{{ansible_env.HOME}}/.asdf/shims:{{ansible_env.PATH}}"

- name: update nodejs {{nodejs_version}} shims
  command: ~/.asdf/bin/asdf reshim nodejs
  changed_when: false
