---
- name: install nim plugin via asdf
  git:
    repo: https://github.com/rfrancis/asdf-nim.git
    dest: ~/.asdf/plugins/nim

- name: install nim {{nim_version}} via asdf
  command: ~/.asdf/bin/asdf install nim v{{nim_version}}
  args:
    creates: ~/.asdf/installs/nim/v{{nim_version}}

- name: set nim {{nim_version}} as default
  command: ~/.asdf/bin/asdf global nim v{{nim_version}}
  changed_when: false

- name: update nim {{nim_version}} shims
  command: ~/.asdf/bin/asdf reshim nim
  changed_when: false
