;; -*- lexical-binding: t; no-native-compile: t -*-

;; Automatic light/dark theme switching.
;;
;; Emacs themes are global, so the surface that most recently reports
;; a change wins.  GUI frames follow the desktop via auto-dark, and
;; TTY frames follow the terminal via CSI 997 with an OSC 11 fallback.

(defgroup gemacs-theme nil
  "Automatic dark/light theme switching."
  :group 'gemacs)

;; Theme loaders and mode policies are generated by colors.nix.
(defvar gemacs-theme-desktop-dark nil
  "Loader for the desktop dark theme.")

(defvar gemacs-theme-desktop-light nil
  "Loader for the desktop light theme.")

(defvar gemacs-theme-terminal-dark nil
  "Loader for the terminal dark theme.")

(defvar gemacs-theme-terminal-light nil
  "Loader for the terminal light theme.")

(defvar gemacs-theme-desktop-mode "auto"
  "Desktop policy: auto, dark, or light.")

(defvar gemacs-theme-terminal-mode "auto"
  "Terminal policy: auto, dark, or light.")

(defvar gemacs-theme--last-context nil
  "Context that last applied a theme.")

(defvar gemacs-theme--last-mode nil
  "Mode last applied by the last context.")


;; Theme dispatch

(defun gemacs-theme--variable (context mode)
  "Return the loader variable for CONTEXT and MODE."
  (intern (format "gemacs-theme-%s-%s"
                  (symbol-name context)
                  (symbol-name mode))))

(defun gemacs-theme--loader-for (context mode)
  "Return the loader function for CONTEXT and MODE."
  (let ((var (gemacs-theme--variable context mode)))
    (and (boundp var) (symbol-value var))))

(defun gemacs-theme--apply (context mode)
  "Apply MODE for CONTEXT.

MODE is the symbol dark or light.  CONTEXT is the symbol desktop or
terminal."
  (when-let ((loader (gemacs-theme--loader-for context mode)))
    (unless (and (eq gemacs-theme--last-context context)
                 (eq gemacs-theme--last-mode mode))
      (mapc #'disable-theme custom-enabled-themes)
      (funcall loader)
      (setq gemacs-theme--last-context context
            gemacs-theme--last-mode mode)
      (setq frame-background-mode mode)
      (mapc #'frame-set-background-mode (frame-list)))))


;; Desktop (GUI)

(defun gemacs-theme--desktop-after-dark ()
  "Apply the desktop dark theme after auto-dark reports dark mode."
  (gemacs-theme--apply 'desktop 'dark))

(defun gemacs-theme--desktop-after-light ()
  "Apply the desktop light theme after auto-dark reports light mode."
  (gemacs-theme--apply 'desktop 'light))

(defun gemacs-theme--desktop-start (&optional _frame)
  "Start desktop theme tracking."
  (if (string= gemacs-theme-desktop-mode "auto")
      (unless auto-dark-mode
        (auto-dark-mode 1))
    (gemacs-theme--apply 'desktop (intern gemacs-theme-desktop-mode))))

(use-package auto-dark
  :demand t
  :preface
  (eval-when-compile
    (declare-function auto-dark-mode nil)
    (declare-function frame-set-background-mode nil)
    (declare-function xterm--query nil)
    (declare-function xterm--read-event-for-query nil)
    (defvar xterm-query-timeout)
    (defvar xterm-query-redisplay-timeout))

  :custom
  ;; Disable auto-dark's theme loading.  Its detection and hooks
  ;; drive gemacs-theme--apply instead.
  (auto-dark-themes nil)
  (auto-dark-polling-interval-seconds 5)

  :config
  (add-hook 'auto-dark-dark-mode-hook #'gemacs-theme--desktop-after-dark)
  (add-hook 'auto-dark-light-mode-hook #'gemacs-theme--desktop-after-light))


;; Terminal (TTY)

(defvar gemacs-theme--tty-got-report nil
  "Non-nil when the current terminal answered a theme query.")

(defun gemacs-theme--tty-report (mode)
  "Handle a terminal report for MODE."
  (setq gemacs-theme--tty-got-report t)
  (gemacs-theme--apply 'terminal mode))

(defun gemacs-theme--tty-report-dark (&optional _prompt)
  "Handle CSI 997 ; 1 n."
  (gemacs-theme--tty-report 'dark))

(defun gemacs-theme--tty-report-light (&optional _prompt)
  "Handle CSI 997 ; 2 n."
  (gemacs-theme--tty-report 'light))

(defun gemacs-theme--tty-background-report ()
  "Handle an OSC 11 background color reply."
  (let ((str "")
        chr)
    (while (and (setq chr (xterm--read-event-for-query))
                (not (equal chr ?\\)))
      (setq str (concat str (string chr))))
    (when (string-match
          "rgb:\\([0-9a-f]+\\)/\\([0-9a-f]+\\)/\\([0-9a-f]+\\)"
          str)
      (let* ((red (string-to-number (match-string 1 str) 16))
             (green (string-to-number (match-string 2 str) 16))
             (blue (string-to-number (match-string 3 str) 16)))
        (gemacs-theme--tty-report
         (if (< (+ red green blue)
                (* .6 (+ 65535 65535 65535)))
             'dark
           'light))))))

(defun gemacs-theme--tty-query-background ()
  "Query OSC 11 and apply the reported terminal background mode."
  (let ((xterm-query-timeout 0.8)
        (xterm-query-redisplay-timeout 0.15))
    (xterm--query
     "\e]11;?\e\\"
     '(("\e]11;" . gemacs-theme--tty-background-report)))))

(defun gemacs-theme--tty-query-scheme ()
  "Detect the terminal theme via CSI 996 with an OSC 11 fallback.

The terminal is queried synchronously, so no entries are left in
the input decoding map."
  (require 'term/xterm)
  (let ((xterm-query-timeout 0.4)
        (xterm-query-redisplay-timeout 0.1))
    (xterm--query
     "\e[?996n"
     '(("\e[?997;1n" . gemacs-theme--tty-report-dark)
       ("\e[?997;2n" . gemacs-theme--tty-report-light))
     t))
  (unless gemacs-theme--tty-got-report
    (gemacs-theme--tty-query-background)))

(defun gemacs-theme--tty-start (frame)
  "Start terminal theme tracking for FRAME."
  (with-selected-frame frame
    (if (string= gemacs-theme-terminal-mode "auto")
        (progn
          (setq gemacs-theme--tty-got-report nil)
          (gemacs-theme--tty-query-scheme))
      (gemacs-theme--apply 'terminal (intern gemacs-theme-terminal-mode)))))


;; Frame integration

(defun gemacs-theme--after-make-frame (frame)
  "Start theme tracking appropriate for FRAME."
  (if (display-graphic-p frame)
      (gemacs-theme--desktop-start frame)
    (gemacs-theme--tty-start frame)))

(defun gemacs-theme--after-focus-change ()
  "Re-sync theme tracking with the surface that just gained focus."
  (if (display-graphic-p)
      (when (string= gemacs-theme-desktop-mode "auto")
        (when (fboundp 'auto-dark--check-and-set-dark-mode)
          (auto-dark--check-and-set-dark-mode)))
    (when (string= gemacs-theme-terminal-mode "auto")
      (gemacs-theme--tty-start (selected-frame)))))

(add-hook 'after-make-frame-functions #'gemacs-theme--after-make-frame)
(add-hook 'after-init-hook
          (lambda ()
            (gemacs-theme--after-make-frame (selected-frame))))
(add-function :after after-focus-change-function #'gemacs-theme--after-focus-change)
