;; -*- lexical-binding: t; no-native-compile: t -*-

;; Automatic light/dark theme switching.
;;
;; Emacs themes are global, so the surface that most recently reports
;; a change wins.  GUI frames follow the desktop via auto-dark, and
;; TTY frames follow the terminal via CSI 997 with an OSC 11 fallback.

(defgroup gemacs-theme nil
  "Automatic dark/light theme switching."
  :group 'gemacs)

;; Theme loaders and mode policies are generated by colors.nix.
(defvar gemacs-theme-desktop-dark nil
  "Loader for the desktop dark theme.")

(defvar gemacs-theme-desktop-light nil
  "Loader for the desktop light theme.")

(defvar gemacs-theme-terminal-dark nil
  "Loader for the terminal dark theme.")

(defvar gemacs-theme-terminal-light nil
  "Loader for the terminal light theme.")

(defvar gemacs-theme-desktop-mode "auto"
  "Desktop policy: auto, dark, or light.")

(defvar gemacs-theme-terminal-mode "auto"
  "Terminal policy: auto, dark, or light.")

(defvar gemacs-theme--last-context nil
  "Context that last applied a theme.")

(defvar gemacs-theme--last-mode nil
  "Mode last applied by the last context.")


;; Theme dispatch

(defun gemacs-theme--variable (context mode)
  "Return the loader variable for CONTEXT and MODE."
  (intern (format "gemacs-theme-%s-%s"
                  (symbol-name context)
                  (symbol-name mode))))

(defun gemacs-theme--loader-for (context mode)
  "Return the loader function for CONTEXT and MODE."
  (let ((var (gemacs-theme--variable context mode)))
    (and (boundp var) (symbol-value var))))

(defun gemacs-theme--apply (context mode)
  "Apply MODE for CONTEXT.

MODE is the symbol dark or light.  CONTEXT is the symbol desktop or
terminal."
  (when-let ((loader (gemacs-theme--loader-for context mode)))
    (unless (and (eq gemacs-theme--last-context context)
                 (eq gemacs-theme--last-mode mode))
      (mapc #'disable-theme custom-enabled-themes)
      (funcall loader)
      (setq gemacs-theme--last-context context
            gemacs-theme--last-mode mode)
      (setq frame-background-mode mode)
      (mapc #'frame-set-background-mode (frame-list)))))


;; Desktop (GUI)

(defun gemacs-theme--desktop-after-dark ()
  "Apply the desktop dark theme after auto-dark reports dark mode."
  (gemacs-theme--apply 'desktop 'dark))

(defun gemacs-theme--desktop-after-light ()
  "Apply the desktop light theme after auto-dark reports light mode."
  (gemacs-theme--apply 'desktop 'light))

(defun gemacs-theme--desktop-start (&optional _frame)
  "Start desktop theme tracking."
  (if (string= gemacs-theme-desktop-mode "auto")
      (unless auto-dark-mode
        (auto-dark-mode 1))
    (gemacs-theme--apply 'desktop (intern gemacs-theme-desktop-mode))))

(use-package auto-dark
  :demand t
  :preface
  (eval-when-compile
    (declare-function auto-dark-mode nil)
    (declare-function frame-set-background-mode nil)
    (declare-function frame-terminal nil)
    (declare-function send-string-to-terminal nil)
    (declare-function xterm--push-map nil)
    (declare-function xterm--query nil)
    (declare-function xterm--read-event-for-query nil)
    (defvar xterm-query-timeout)
    (defvar xterm-query-redisplay-timeout)
    (defvar help-event-list))

  :custom
  ;; Disable auto-dark's theme loading.  Its detection and hooks
  ;; drive gemacs-theme--apply instead.
  (auto-dark-themes nil)
  (auto-dark-polling-interval-seconds 5)

  :config
  (add-hook 'auto-dark-dark-mode-hook #'gemacs-theme--desktop-after-dark)
  (add-hook 'auto-dark-light-mode-hook #'gemacs-theme--desktop-after-light))


;; Terminal (TTY)

(defvar gemacs-theme--tty-got-report nil
  "Non-nil when the current terminal answered a theme query.")

(defun gemacs-theme--tty-report (mode)
  "Handle a terminal report for MODE."
  (setq gemacs-theme--tty-got-report t)
  (gemacs-theme--apply 'terminal mode))

(defun gemacs-theme--tty-report-dark (&optional _prompt)
  "Handle CSI 997 ; 1 n."
  (gemacs-theme--tty-report 'dark)
  [])

(defun gemacs-theme--tty-report-light (&optional _prompt)
  "Handle CSI 997 ; 2 n."
  (gemacs-theme--tty-report 'light)
  [])

(defun gemacs-theme--tty-report-none (&optional _prompt)
  "Handle CSI 997 ; 0 n, meaning no color scheme is set."
  (setq gemacs-theme--tty-got-report t)
  [])

(defun gemacs-theme--tty-background-report ()
  "Handle an OSC 11 background color reply."
  (let ((str "")
        chr)
    (while (and (setq chr (xterm--read-event-for-query))
                (not (equal chr ?\\)))
      (setq str (concat str (string chr))))
    (when (string-match
          "rgb:\\([0-9a-f]+\\)/\\([0-9a-f]+\\)/\\([0-9a-f]+\\)"
          str)
      (let* ((red (string-to-number (match-string 1 str) 16))
             (green (string-to-number (match-string 2 str) 16))
             (blue (string-to-number (match-string 3 str) 16)))
        (gemacs-theme--tty-report
         (if (< (+ red green blue)
                (* .6 (+ 65535 65535 65535)))
             'dark
           'light))))))

(defun gemacs-theme--tty-query-background ()
  "Query OSC 11 and apply the reported terminal background mode."
  (let ((xterm-query-timeout 0.8)
        (xterm-query-redisplay-timeout 0.15))
    (xterm--query
     "\e]11;?\e\\"
     '(("\e]11;" . gemacs-theme--tty-background-report)))))

(defvar gemacs-theme--tty-decode-map
  (let ((map (make-sparse-keymap)))
    (define-key map "\e[?997;0n" #'gemacs-theme--tty-report-none)
    (define-key map "\e[?997;1n" #'gemacs-theme--tty-report-dark)
    (define-key map "\e[?997;2n" #'gemacs-theme--tty-report-light)
    map)
  "Keymap decoding CSI 997 color-scheme reports from the terminal.")

(defvar gemacs-theme--tty-handlers-installed nil
  "Non-nil when the CSI 997 input handlers are installed.")

(defun gemacs-theme--tty-install-handlers ()
  "Decode CSI 997 color-scheme reports in the input decoding map.

The handlers are installed through keymap inheritance, the same way
Emacs installs xterm-function-map, so they coexist with arrow and
function-key decoders.

The ? character (0x3f) is a member of help-event-list by default, so
read-key-sequence treats ESC [ ? as a prefix followed by a help key and
pops up the prefix binding help buffer instead of decoding the report.
Remove ? from help-event-list so the report is decoded normally."
  (unless gemacs-theme--tty-handlers-installed
    (setq help-event-list (delq ?\? help-event-list))
    (xterm--push-map gemacs-theme--tty-decode-map input-decode-map)
    (setq gemacs-theme--tty-handlers-installed t)))

(defun gemacs-theme--tty-request-updates (frame)
  "Ask FRAME's terminal for unsolicited color-scheme reports."
  (send-string-to-terminal "\e[?2031h" (frame-terminal frame)))

(defun gemacs-theme--tty-sync (frame)
  "Query FRAME's terminal for its current color scheme.

Falls back to an OSC 11 background query when the terminal does not
answer the CSI 996 query."
  (with-selected-frame frame
    (setq gemacs-theme--tty-got-report nil)
    (send-string-to-terminal "\e[?996n")
    (run-with-timer
     0.4 nil
     (lambda (f)
       (when (and (frame-live-p f) (not gemacs-theme--tty-got-report))
         (with-selected-frame f
           (gemacs-theme--tty-query-background))))
     frame)))

(defun gemacs-theme--tty-start (frame)
  "Start terminal theme tracking for FRAME."
  (require 'term/xterm)
  (gemacs-theme--tty-install-handlers)
  (with-selected-frame frame
    (if (string= gemacs-theme-terminal-mode "auto")
        (progn
          (gemacs-theme--tty-request-updates frame)
          (gemacs-theme--tty-sync frame))
      (gemacs-theme--apply 'terminal (intern gemacs-theme-terminal-mode)))))


;; Frame integration

(defun gemacs-theme--after-make-frame (frame)
  "Start theme tracking appropriate for FRAME."
  (if (display-graphic-p frame)
      (gemacs-theme--desktop-start frame)
    (gemacs-theme--tty-start frame)))

(defun gemacs-theme--after-focus-change ()
  "Re-sync theme tracking with the surface that just gained focus."
  (if (display-graphic-p)
      (when (string= gemacs-theme-desktop-mode "auto")
        (when (fboundp 'auto-dark--check-and-set-dark-mode)
          (auto-dark--check-and-set-dark-mode)))
    (when (string= gemacs-theme-terminal-mode "auto")
      (gemacs-theme--tty-start (selected-frame)))))

(add-hook 'after-make-frame-functions #'gemacs-theme--after-make-frame)
(add-hook 'after-init-hook
          (lambda ()
            (gemacs-theme--after-make-frame (selected-frame))))
(add-function :after after-focus-change-function #'gemacs-theme--after-focus-change)
