---
- name: install golang plugin via asdf
  git:
    repo: https://github.com/kennyp/asdf-golang.git
    dest: ~/.asdf/plugins/golang

- name: install golang {{golang_version}} via asdf
  command: ~/.asdf/bin/asdf install golang {{golang_version}}
  args:
    creates: ~/.asdf/installs/golang/{{golang_version}}

- name: set golang {{golang_version}} as default
  command: ~/.asdf/bin/asdf global golang {{golang_version}}
  changed_when: false

- name: ensure gopath directory
  file:
    path: ~/Dev/go/
    state: directory
    recurse: yes

- name: install golang packages
  command: ~/.asdf/installs/golang/{{golang_version}}/go/bin/go get -u -v {{item}}
  args:
    creates: "~/Dev/go/src/{{item}}"
  environment:
    GOPATH: "{{ansible_env.HOME}}/Dev/go/"
    GOROOT: "{{ansible_env.HOME}}/.asdf/installs/golang/{{golang_version}}/go"
  with_items: "{{golang_packages}}"

- name: update golang {{golang_version}} shims
  command: ~/.asdf/bin/asdf reshim golang
  changed_when: false
