---
- name: install helm plugin via asdf
  git:
    repo: https://github.com/Antiarchitect/asdf-helm.git
    dest: ~/.asdf/plugins/helm

- name: install helm {{helm_version}} via asdf
  command: ~/.asdf/bin/asdf install helm {{helm_version}}
  args:
    creates: ~/.asdf/installs/helm/{{helm_version}}

- name: set helm {{helm_version}} as default
  command: ~/.asdf/bin/asdf global helm {{helm_version}}
  changed_when: false

- name: update helm {{helm_version}} shims
  command: ~/.asdf/bin/asdf reshim helm
  changed_when: false
