---
- name: install kubectl plugin via asdf
  git:
    repo: https://github.com/Banno/asdf-kubectl.git
    dest: ~/.asdf/plugins/kubectl

- name: install kubectl {{kubectl_version}} via asdf
  command: ~/.asdf/bin/asdf install kubectl {{kubectl_version}}
  args:
    creates: ~/.asdf/installs/kubectl/{{kubectl_version}}

- name: set kubectl {{kubectl_version}} as default
  command: ~/.asdf/bin/asdf global kubectl {{kubectl_version}}
  changed_when: false

- name: update kubectl {{kubectl_version}} shims
  command: ~/.asdf/bin/asdf reshim kubectl
  changed_when: false
