---
- name: install minikube plugin via asdf
  git:
    repo: https://github.com/alvarobp/asdf-minikube.git
    dest: ~/.asdf/plugins/minikube

- name: install minikube {{minikube_version}} via asdf
  command: ~/.asdf/bin/asdf install minikube {{minikube_version}}
  args:
    creates: ~/.asdf/installs/minikube/{{minikube_version}}

- name: set minikube {{minikube_version}} as default
  command: ~/.asdf/bin/asdf global minikube {{minikube_version}}
  changed_when: false

- name: update minikube {{minikube_version}} shims
  command: ~/.asdf/bin/asdf reshim minikube
  changed_when: false
