---
- name: install ruby plugin via asdf
  git:
    repo: https://github.com/asdf-vm/asdf-ruby.git
    dest: ~/.asdf/plugins/ruby

- name: install ruby {{ruby_version}} via asdf
  command: ~/.asdf/bin/asdf install ruby {{ruby_version}}
  args:
    creates: ~/.asdf/installs/ruby/{{ruby_version}}

- name: set ruby {{ruby_version}} as default
  command: ~/.asdf/bin/asdf global ruby {{ruby_version}}
  changed_when: false

- name: install ruby packages
  gem:
    name: "{{item}}"
    state: latest
    user_install: false
    executable: ~/.asdf/installs/ruby/{{ruby_version}}/bin/gem
  with_items: "{{ruby_packages}}"

- name: update ruby {{ruby_version}} shims
  command: ~/.asdf/bin/asdf reshim ruby
  changed_when: false
