#!/usr/bin/env zsh

eval set -- "$@"

unset _tmux_flag
unset _session_name

while true; do
    case "$1" in
        -CC ) _tmux_flag="$1"; shift;;
        *   ) _session_name="$1"; break;;
    esac
done

if [[ $# > 0 ]]; then
    shift
fi

if [[ ${TMUX:-} ]]; then
    echo "tmux-shell cannot be used within tmux session"
    echo "use <C-b>:switch-client -t to switch to other session"
    echo "or <C-b>:new-session -A -s name to create a new session"
else
    exec tmux $_tmux_flag new-session -A -s "${_session_name:-main}" $@
fi
