---
- name: install unbound service
  become: yes
  pacman: name=unbound state=latest
  notify:
    - restart unbound systemd service

- name: ensure unbound directory
  become: yes
  file: path=/etc/unbound state=directory recurse=yes

- name: update resolvconf configuration
  become: yes
  copy:
    src: unbound/resolvconf.conf
    dest: "/etc/resolvconf.conf"
  register: update_resolvconf

- name: reload resolvconf
  become: yes
  command: resolvconf -u
  when: update_resolvconf.changed

- name: ensure unbound anchor
  become: yes
  become_user: unbound
  shell: /usr/sbin/unbound-anchor -a /etc/unbound/root.key
  args:
    creates: /etc/unbound/root.key
  register: unbound_anchor
  failed_when: unbound_anchor.rc >= 2

- name: update unbound configuration
  become: yes
  template:
    src: unbound/unbound.conf.j2
    dest: "/etc/unbound/unbound.conf"
  notify:
    - restart unbound systemd service

- name: enable unbound service
  become: yes
  systemd:
    name: "unbound"
    enabled: yes
    state: started
