/**
 * Smart Compact Extension for Pi Coding Agent
 *
 * Uses a configurable model for session compaction instead of the default model.
 * The provider/model pair is read from custom.json generated by Nix config.
 * Falls back to default compaction if the configured model is unavailable.
 */

import { complete } from "@mariozechner/pi-ai";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import {
  convertToLlm,
  serializeConversation,
} from "@mariozechner/pi-coding-agent";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const configPath = path.join(os.homedir(), ".pi/agent/custom.json");

interface CompactionModelConfig {
  provider: string;
  model: string;
}

interface CustomConfig {
  compactionModel?: CompactionModelConfig | null;
}

let compactionConfig: CompactionModelConfig | null = null;

try {
  if (fs.existsSync(configPath)) {
    const customConfig: CustomConfig = JSON.parse(
      fs.readFileSync(configPath, "utf-8"),
    );
    if (customConfig.compactionModel) {
      compactionConfig = customConfig.compactionModel;
    }
  }
} catch {
  // Config missing or invalid - extension will be a no-op
}

export default function (pi: ExtensionAPI) {
  // Skip if no config
  if (!compactionConfig) {
    return;
  }

  pi.on("session_before_compact", async (event, ctx) => {
    const { preparation, signal } = event;
    const {
      messagesToSummarize,
      turnPrefixMessages,
      tokensBefore,
      firstKeptEntryId,
      previousSummary,
    } = preparation;

    // Resolve the configured model
    const model = ctx.modelRegistry.find(
      compactionConfig!.provider,
      compactionConfig!.model,
    );
    if (!model) {
      ctx.ui.notify(
        `Compaction model "${compactionConfig!.provider}/${compactionConfig!.model}" not found, using default`,
        "warning",
      );
      return;
    }

    // Get API key
    const apiKey = await ctx.modelRegistry.getApiKey(model);
    if (!apiKey) {
      ctx.ui.notify(
        `No API key for ${compactionConfig!.provider}, using default compaction`,
        "warning",
      );
      return;
    }

    // Combine all messages for summary
    const allMessages = [...messagesToSummarize, ...turnPrefixMessages];

    ctx.ui.notify(
      `Compacting ${tokensBefore.toLocaleString()} tokens with ${model.id}...`,
      "info",
    );

    // Convert messages to readable text format
    const conversationText = serializeConversation(convertToLlm(allMessages));

    // Include previous summary context if available
    const previousContext = previousSummary
      ? `\n\nPrevious session summary for context:\n${previousSummary}`
      : "";

    // Build messages that ask for a comprehensive summary
    const summaryMessages = [
      {
        role: "user" as const,
        content: [
          {
            type: "text" as const,
            text: `You are a session compaction expert for an AI coding agent. Your goal is to create a "Checkpoint Summary" that enables another agent to resume work with zero loss of technical context.

Include the following in your summary:${previousContext}

### 1. Primary Objective
- Clear statement of the current goal and any background context provided by the user.

### 2. Technical Decisions & Findings
- Key architectural choices or logic implemented.
- Critical findings from codebase research or documentation (e.g., "Library X doesn't support Y").

### 3. Execution History
- **Commands**: List specific shell commands used (e.g., git, nix, npm) and their results if they changed state or provided critical info.
- **Files**: List files modified or created. Be specific about what was changed in each.

### 4. Current Progress & State
- What is finished and verified?
- What is currently being worked on?
- Precise "in-flight" state: Are there open files with unsaved/unverified changes? Is there a failing test?

### 5. Blockers & Open Questions
- Any issues encountered that weren't resolved.
- Things the user needs to clarify.

### 6. Next Actions
- The immediate next 2-3 steps to continue the implementation.

**Constraint**: Be technical, dense, and precise. Prefer code snippets, paths, and exact error messages over vague descriptions. The summary replaces the entire history; if it's not here, it's lost.

Format the summary as structured markdown with clear sections.

<conversation>
${conversationText}
</conversation>`,
          },
        ],
        timestamp: Date.now(),
      },
    ];

    try {
      // Pass signal to honor abort requests
      const response = await complete(
        model,
        { messages: summaryMessages },
        {
          apiKey,
          maxTokens: model.maxTokens,
          signal,
        },
      );

      const summary = response.content
        .filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");

      if (!summary.trim()) {
        if (!signal.aborted) {
          ctx.ui.notify(
            "Compaction summary was empty, using default",
            "warning",
          );
        }
        return;
      }

      // Return compaction content
      return {
        compaction: {
          summary,
          firstKeptEntryId,
          tokensBefore,
        },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      ctx.ui.notify(`Compaction failed: ${message}, using default`, "error");
      // Fall back to default compaction on error
      return;
    }
  });
}
