#!/bin/sh -e
#
# Script to setup X session.
#

# shellcheck source=../sh/profile
if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
fi


## Utils
##

run_background() {
    pidname=$1; shift

    rundir="$HOME/.local/run"
    pidfile="$rundir/$pidname"
    mkdir -p "$rundir"

    if [ -f "$pidfile" ]; then
        pid=$(cat "$pidfile")

        # BusyBox ps doesn't have ps -p
        if [ -d /proc ] && [ ! -d /proc/"$pid" ]; then
            rm "$pidfile"
        elif ! ps -o pid= -p "$pid" >/dev/null; then
            rm "$pidfile"
        fi
    fi

    if [ ! -f "$pidfile" ]; then
        "$@" &
        echo "$!" > "$pidfile"
    fi
}


## Xrdb
##

for f in "$HOME/.Xresources" "$HOME/.Xresources.local"; do
    if [ -f "$f" ]; then
        xrdb -merge "$f"
    fi
done


## Desktop
##

xset b off || true
xsetroot -solid "#2f3640" || true
if command -v feh >/dev/null && [ -f "$HOME/.wallpaper" ]; then
    feh --bg-fill "$HOME/.wallpaper" &
fi


## Helper programs
##

# Window composition; should be disabled on low powered device such as
# Intel Compute Stick, otherwise screen drawing would be really slow.
if command -v compton >/dev/null; then
    compton -b
fi

# Adjust display temperature
if command -v redshift >/dev/null && [ -f "$HOME/.config/redshift.cfg" ]; then
    if [ -f "$HOME/.local/run/redshift.pid" ]; then
        kill $(cat "$HOME/.local/run/redshift.pid")
    fi

    run_background \
        redshift.pid \
        redshift -c "$HOME/.config/redshift.cfg"
fi

# VMware clipboard sharing for OpenBSD
if command -v vmwh >/dev/null; then
    run_background \
        vmwh.pid \
        vmwh
fi


## WM
##

exec cwm
