---
- hosts: all
  tasks:
    - import_role:
        name: console
      tags:
        - console

    - import_role:
        name: services
      tags:
        - services

    - import_role:
        name: desktop
      tags:
        - desktop
