ENV['VAGRANT_INSTALLER_ENV'] = "1"

Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    config.vm.provider :libvirt do |libvirt, override|
        libvirt.qemu_use_session = true

        libvirt.graphics_type = "none"
        libvirt.cpu_model = "host-passthrough"
        libvirt.cpu_fallback = "forbid"

        libvirt.cpus = 2
        libvirt.memory = 2048
    end
end
