---
- name: ensure launch agents directory
  file:
    path: ~/Library/LaunchAgents
    state: directory
    recurse: yes

- include_tasks: "darwin/dnscrypt-proxy.yml"
- include_tasks: "darwin/unbound.yml"
- include_tasks: "darwin/user-env.yml"
