---
- name: prepare dot directories
  file: path={{item}} state=directory recurse=yes
  with_items: "{{dots}}"

- name: prepare arch-specific dot directories
  file: path={{item}} state=directory recurse=yes
  with_items: "{{archlinux_dots}}"
  when: ansible_os_family == "Archlinux"

- name: link files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{links}}"

- name: link darwin-specific files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{darwin_links}}"
  when: ansible_os_family == "Darwin"

- name: link arch-specific files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{archlinux_links}}"
  when: ansible_os_family == "Archlinux"
