---
- name: initialize chunkwm taps
  homebrew_tap: tap={{item}} state=present
  with_items:
    - crisidev/chunkwm
    - koekeishiya/formulae

- name: ensure chunkwm directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/.local/var/logs

- name: install chunkwm
  homebrew: name=chunkwm state=latest
  notify:
    - restart chunkwm launchd service

- name: install skhd
  homebrew: name=skhd state=latest
  notify:
    - restart skhd launchd service

- name: enable chunkwm service
  template:
    src: chunkwm/io.github.koekeishiya.chunkwm.plist.j2
    dest: ~/Library/LaunchAgents/io.github.koekeishiya.chunkwm.plist
  notify:
    - restart chunkwm launchd service

- name: enable skhd service
  template:
    src: chunkwm/io.github.koekeishiya.skhd.plist.j2
    dest: ~/Library/LaunchAgents/io.github.koekeishiya.skhd.plist
  notify:
    - restart skhd launchd service
