---
- name: install unbound service
  homebrew: name=unbound state=latest
  notify:
    - unload unbound launchd service
    - load unbound launchd service

- name: ensure unbound directories
  file: path={{item}} state=directory recurse=yes
  with_items:
    - ~/.local/etc/unbound
    - ~/.local/var/log

- name: update unbound configurations
  template:
    src: home/local/etc/unbound/unbound.conf.j2
    dest: "{{ansible_env['HOME']}}/.local/etc/unbound/unbound.conf"
  notify:
    - unload unbound launchd service
    - load unbound launchd service

- name: enable unbound service
  template:
    src: home/Library/LaunchAgents/net.unbound.unbound.plist.j2
    dest: ~/Library/LaunchAgents/net.unbound.unbound.plist
  register: unbound_enabled

- name: ensure resolver directory
  become: yes
  file:
    path: /etc/resolver
    state: directory
    recurse: yes

- name: add dev resolvers
  become: yes
  copy:
    src: etc/resolver/devel
    dest: /etc/resolver/devel
