# System detection
if [[ -z "${OSTYPE:#darwin*}" ]]; then
    export is_osx=1
    export is_bsd=1
elif [[ -z "${OSTYPE:#bsd*}" ]]; then export is_bsd=1
elif [[ -z "${OSTYPE:#linux*}" ]]; then export is_linux=1
fi

# zsh.d
for zshrc_snipplet in ~/.dotfiles/zsh/zsh.d/S[0-9][0-9]*[^~] ; do
    source $zshrc_snipplet
done