#!/usr/bin/env zsh
#
# ~/.zshrc
#

source ~/.zplug/init.zsh

zplug "zplug/zplug", hook-build:'zplug --self-manage'

zplug "b4b4r07/enhancd", use:init.sh
zplug "zsh-users/zsh-completions", defer:2
zplug "Valodim/zsh-curl-completion", defer:2
zplug "zsh-users/zsh-autosuggestions", defer:2

zplug "~/.dotfiles/zsh/config", from:local, defer:3

if [ -d ~/.dotpriv/zsh/config ]; then
    zplug "~/.dotpriv/zsh/config", from:local, defer:3
fi

zplug "b4b4r07/zsh-gomi", defer:3
zplug "supercrabtree/k", defer:3
zplug "motemen/ghq", defer:3, as:command, from:github, hook-build:'go get -d && go build'
zplug "knqyf263/pet", defer:3, as:command, from:github, hook-build:'go get -d && go build'
zplug "junegunn/fzf", defer:3, as:command, from:github, hook-build:'go get -d && go build'

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

bindkey -e
zplug load

# vim:ft=sh
