#!/usr/bin/env zsh
#
# ~/.zshrc
#

source ~/.zplug/init.zsh

zplug "zplug/zplug", hook-build:'zplug --self-manage'

zplug "lib/spectrum", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "b4b4r07/enhancd", use:init.sh

zplug "zsh-users/zsh-autosuggestions", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2
zplug "zsh-users/zsh-syntax-highlighting", defer:3

zplug "~/.dotfiles/zsh/config", from:local, defer:3

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# vim:ft=sh
