---
- name: install prerequisites
  homebrew_cask: name=java,xquartz state=present

- name: link darwin-specific files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{dots_desktop_darwin}}"
  when: dots_desktop_darwin

- include_tasks: darwin/homebrew.yml
- include_tasks: darwin/cask.yml
- include_tasks: darwin/mas.yml
- include_tasks: darwin/chunkwm.yml
