---
- name: install prerequisites
  homebrew_cask: name=java,xquartz state=present

- name: initialize brew desktop taps
  homebrew_tap: tap={{brew_desktop_taps}} state=present

- name: install homebrew desktop packages
  homebrew: name={{brew_desktop_packages}} state=present

- name: initialize cask taps
  homebrew_tap: tap={{cask_taps}} state=present

- name: install cask packages
  homebrew_cask: name={{cask_packages}} state=present

- name: install mas-cli
  homebrew: name=mas state=latest

- name: initialize mac app store apps
  command: mas install "{{item.id}}"
  with_items: "{{mas_packages}}"
  args:
    creates: "/Applications/{{item.app}}.app"

- name: link darwin-specific files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{dots_desktop_darwin}}"
  when: dots_desktop_darwin
